// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ScoresColumns holds the columns for the "scores" table.
	ScoresColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "keystrokes", Type: field.TypeInt},
		{Name: "accuracy", Type: field.TypeFloat64},
		{Name: "score", Type: field.TypeFloat64},
		{Name: "started_at", Type: field.TypeTime},
		{Name: "ended_at", Type: field.TypeTime},
		{Name: "user_scores", Type: field.TypeInt, Nullable: true},
	}
	// ScoresTable holds the schema information for the "scores" table.
	ScoresTable = &schema.Table{
		Name:       "scores",
		Columns:    ScoresColumns,
		PrimaryKey: []*schema.Column{ScoresColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "scores_users_scores",
				Columns:    []*schema.Column{ScoresColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "mail_adress", Type: field.TypeString, Size: 255},
		{Name: "handle_name", Type: field.TypeString, Size: 255},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "hashed_password", Type: field.TypeString, Size: 255},
		{Name: "department", Type: field.TypeEnum, Enums: []string{"CS", "BI", "IA"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ScoresTable,
		UsersTable,
	}
)

func init() {
	ScoresTable.ForeignKeys[0].RefTable = UsersTable
}
