// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ent/ent/predicate"
	"ent/ent/score"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ScoreUpdate is the builder for updating Score entities.
type ScoreUpdate struct {
	config
	hooks    []Hook
	mutation *ScoreMutation
}

// Where appends a list predicates to the ScoreUpdate builder.
func (su *ScoreUpdate) Where(ps ...predicate.Score) *ScoreUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetKeystrokes sets the "keystrokes" field.
func (su *ScoreUpdate) SetKeystrokes(i int) *ScoreUpdate {
	su.mutation.ResetKeystrokes()
	su.mutation.SetKeystrokes(i)
	return su
}

// SetNillableKeystrokes sets the "keystrokes" field if the given value is not nil.
func (su *ScoreUpdate) SetNillableKeystrokes(i *int) *ScoreUpdate {
	if i != nil {
		su.SetKeystrokes(*i)
	}
	return su
}

// AddKeystrokes adds i to the "keystrokes" field.
func (su *ScoreUpdate) AddKeystrokes(i int) *ScoreUpdate {
	su.mutation.AddKeystrokes(i)
	return su
}

// SetAccuracy sets the "accuracy" field.
func (su *ScoreUpdate) SetAccuracy(f float64) *ScoreUpdate {
	su.mutation.ResetAccuracy()
	su.mutation.SetAccuracy(f)
	return su
}

// SetNillableAccuracy sets the "accuracy" field if the given value is not nil.
func (su *ScoreUpdate) SetNillableAccuracy(f *float64) *ScoreUpdate {
	if f != nil {
		su.SetAccuracy(*f)
	}
	return su
}

// AddAccuracy adds f to the "accuracy" field.
func (su *ScoreUpdate) AddAccuracy(f float64) *ScoreUpdate {
	su.mutation.AddAccuracy(f)
	return su
}

// SetScore sets the "score" field.
func (su *ScoreUpdate) SetScore(f float64) *ScoreUpdate {
	su.mutation.ResetScore()
	su.mutation.SetScore(f)
	return su
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (su *ScoreUpdate) SetNillableScore(f *float64) *ScoreUpdate {
	if f != nil {
		su.SetScore(*f)
	}
	return su
}

// AddScore adds f to the "score" field.
func (su *ScoreUpdate) AddScore(f float64) *ScoreUpdate {
	su.mutation.AddScore(f)
	return su
}

// SetStartedAt sets the "startedAt" field.
func (su *ScoreUpdate) SetStartedAt(t time.Time) *ScoreUpdate {
	su.mutation.SetStartedAt(t)
	return su
}

// SetNillableStartedAt sets the "startedAt" field if the given value is not nil.
func (su *ScoreUpdate) SetNillableStartedAt(t *time.Time) *ScoreUpdate {
	if t != nil {
		su.SetStartedAt(*t)
	}
	return su
}

// SetEndedAt sets the "endedAt" field.
func (su *ScoreUpdate) SetEndedAt(t time.Time) *ScoreUpdate {
	su.mutation.SetEndedAt(t)
	return su
}

// SetNillableEndedAt sets the "endedAt" field if the given value is not nil.
func (su *ScoreUpdate) SetNillableEndedAt(t *time.Time) *ScoreUpdate {
	if t != nil {
		su.SetEndedAt(*t)
	}
	return su
}

// Mutation returns the ScoreMutation object of the builder.
func (su *ScoreUpdate) Mutation() *ScoreMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *ScoreUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *ScoreUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *ScoreUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *ScoreUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *ScoreUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(score.Table, score.Columns, sqlgraph.NewFieldSpec(score.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Keystrokes(); ok {
		_spec.SetField(score.FieldKeystrokes, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedKeystrokes(); ok {
		_spec.AddField(score.FieldKeystrokes, field.TypeInt, value)
	}
	if value, ok := su.mutation.Accuracy(); ok {
		_spec.SetField(score.FieldAccuracy, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.AddedAccuracy(); ok {
		_spec.AddField(score.FieldAccuracy, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.Score(); ok {
		_spec.SetField(score.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.AddedScore(); ok {
		_spec.AddField(score.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.StartedAt(); ok {
		_spec.SetField(score.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := su.mutation.EndedAt(); ok {
		_spec.SetField(score.FieldEndedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{score.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// ScoreUpdateOne is the builder for updating a single Score entity.
type ScoreUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScoreMutation
}

// SetKeystrokes sets the "keystrokes" field.
func (suo *ScoreUpdateOne) SetKeystrokes(i int) *ScoreUpdateOne {
	suo.mutation.ResetKeystrokes()
	suo.mutation.SetKeystrokes(i)
	return suo
}

// SetNillableKeystrokes sets the "keystrokes" field if the given value is not nil.
func (suo *ScoreUpdateOne) SetNillableKeystrokes(i *int) *ScoreUpdateOne {
	if i != nil {
		suo.SetKeystrokes(*i)
	}
	return suo
}

// AddKeystrokes adds i to the "keystrokes" field.
func (suo *ScoreUpdateOne) AddKeystrokes(i int) *ScoreUpdateOne {
	suo.mutation.AddKeystrokes(i)
	return suo
}

// SetAccuracy sets the "accuracy" field.
func (suo *ScoreUpdateOne) SetAccuracy(f float64) *ScoreUpdateOne {
	suo.mutation.ResetAccuracy()
	suo.mutation.SetAccuracy(f)
	return suo
}

// SetNillableAccuracy sets the "accuracy" field if the given value is not nil.
func (suo *ScoreUpdateOne) SetNillableAccuracy(f *float64) *ScoreUpdateOne {
	if f != nil {
		suo.SetAccuracy(*f)
	}
	return suo
}

// AddAccuracy adds f to the "accuracy" field.
func (suo *ScoreUpdateOne) AddAccuracy(f float64) *ScoreUpdateOne {
	suo.mutation.AddAccuracy(f)
	return suo
}

// SetScore sets the "score" field.
func (suo *ScoreUpdateOne) SetScore(f float64) *ScoreUpdateOne {
	suo.mutation.ResetScore()
	suo.mutation.SetScore(f)
	return suo
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (suo *ScoreUpdateOne) SetNillableScore(f *float64) *ScoreUpdateOne {
	if f != nil {
		suo.SetScore(*f)
	}
	return suo
}

// AddScore adds f to the "score" field.
func (suo *ScoreUpdateOne) AddScore(f float64) *ScoreUpdateOne {
	suo.mutation.AddScore(f)
	return suo
}

// SetStartedAt sets the "startedAt" field.
func (suo *ScoreUpdateOne) SetStartedAt(t time.Time) *ScoreUpdateOne {
	suo.mutation.SetStartedAt(t)
	return suo
}

// SetNillableStartedAt sets the "startedAt" field if the given value is not nil.
func (suo *ScoreUpdateOne) SetNillableStartedAt(t *time.Time) *ScoreUpdateOne {
	if t != nil {
		suo.SetStartedAt(*t)
	}
	return suo
}

// SetEndedAt sets the "endedAt" field.
func (suo *ScoreUpdateOne) SetEndedAt(t time.Time) *ScoreUpdateOne {
	suo.mutation.SetEndedAt(t)
	return suo
}

// SetNillableEndedAt sets the "endedAt" field if the given value is not nil.
func (suo *ScoreUpdateOne) SetNillableEndedAt(t *time.Time) *ScoreUpdateOne {
	if t != nil {
		suo.SetEndedAt(*t)
	}
	return suo
}

// Mutation returns the ScoreMutation object of the builder.
func (suo *ScoreUpdateOne) Mutation() *ScoreMutation {
	return suo.mutation
}

// Where appends a list predicates to the ScoreUpdate builder.
func (suo *ScoreUpdateOne) Where(ps ...predicate.Score) *ScoreUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *ScoreUpdateOne) Select(field string, fields ...string) *ScoreUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Score entity.
func (suo *ScoreUpdateOne) Save(ctx context.Context) (*Score, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *ScoreUpdateOne) SaveX(ctx context.Context) *Score {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *ScoreUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *ScoreUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *ScoreUpdateOne) sqlSave(ctx context.Context) (_node *Score, err error) {
	_spec := sqlgraph.NewUpdateSpec(score.Table, score.Columns, sqlgraph.NewFieldSpec(score.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Score.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, score.FieldID)
		for _, f := range fields {
			if !score.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != score.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Keystrokes(); ok {
		_spec.SetField(score.FieldKeystrokes, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedKeystrokes(); ok {
		_spec.AddField(score.FieldKeystrokes, field.TypeInt, value)
	}
	if value, ok := suo.mutation.Accuracy(); ok {
		_spec.SetField(score.FieldAccuracy, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.AddedAccuracy(); ok {
		_spec.AddField(score.FieldAccuracy, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.Score(); ok {
		_spec.SetField(score.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.AddedScore(); ok {
		_spec.AddField(score.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.StartedAt(); ok {
		_spec.SetField(score.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := suo.mutation.EndedAt(); ok {
		_spec.SetField(score.FieldEndedAt, field.TypeTime, value)
	}
	_node = &Score{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{score.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
