// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Score is the predicate function for score builders.
type Score func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
