// Code generated by ent, DO NOT EDIT.

package score

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/su-its/typing/typing-server/domain/repository/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Score {
	return predicate.Score(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Score {
	return predicate.Score(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Score {
	return predicate.Score(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Score {
	return predicate.Score(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Score {
	return predicate.Score(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Score {
	return predicate.Score(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Score {
	return predicate.Score(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Score {
	return predicate.Score(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Score {
	return predicate.Score(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Score {
	return predicate.Score(sql.FieldEQ(FieldUserID, v))
}

// Keystrokes applies equality check predicate on the "keystrokes" field. It's identical to KeystrokesEQ.
func Keystrokes(v int) predicate.Score {
	return predicate.Score(sql.FieldEQ(FieldKeystrokes, v))
}

// Accuracy applies equality check predicate on the "accuracy" field. It's identical to AccuracyEQ.
func Accuracy(v float64) predicate.Score {
	return predicate.Score(sql.FieldEQ(FieldAccuracy, v))
}

// IsMaxKeystrokes applies equality check predicate on the "is_max_keystrokes" field. It's identical to IsMaxKeystrokesEQ.
func IsMaxKeystrokes(v bool) predicate.Score {
	return predicate.Score(sql.FieldEQ(FieldIsMaxKeystrokes, v))
}

// IsMaxAccuracy applies equality check predicate on the "is_max_accuracy" field. It's identical to IsMaxAccuracyEQ.
func IsMaxAccuracy(v bool) predicate.Score {
	return predicate.Score(sql.FieldEQ(FieldIsMaxAccuracy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Score {
	return predicate.Score(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Score {
	return predicate.Score(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Score {
	return predicate.Score(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Score {
	return predicate.Score(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Score {
	return predicate.Score(sql.FieldNotIn(FieldUserID, vs...))
}

// KeystrokesEQ applies the EQ predicate on the "keystrokes" field.
func KeystrokesEQ(v int) predicate.Score {
	return predicate.Score(sql.FieldEQ(FieldKeystrokes, v))
}

// KeystrokesNEQ applies the NEQ predicate on the "keystrokes" field.
func KeystrokesNEQ(v int) predicate.Score {
	return predicate.Score(sql.FieldNEQ(FieldKeystrokes, v))
}

// KeystrokesIn applies the In predicate on the "keystrokes" field.
func KeystrokesIn(vs ...int) predicate.Score {
	return predicate.Score(sql.FieldIn(FieldKeystrokes, vs...))
}

// KeystrokesNotIn applies the NotIn predicate on the "keystrokes" field.
func KeystrokesNotIn(vs ...int) predicate.Score {
	return predicate.Score(sql.FieldNotIn(FieldKeystrokes, vs...))
}

// KeystrokesGT applies the GT predicate on the "keystrokes" field.
func KeystrokesGT(v int) predicate.Score {
	return predicate.Score(sql.FieldGT(FieldKeystrokes, v))
}

// KeystrokesGTE applies the GTE predicate on the "keystrokes" field.
func KeystrokesGTE(v int) predicate.Score {
	return predicate.Score(sql.FieldGTE(FieldKeystrokes, v))
}

// KeystrokesLT applies the LT predicate on the "keystrokes" field.
func KeystrokesLT(v int) predicate.Score {
	return predicate.Score(sql.FieldLT(FieldKeystrokes, v))
}

// KeystrokesLTE applies the LTE predicate on the "keystrokes" field.
func KeystrokesLTE(v int) predicate.Score {
	return predicate.Score(sql.FieldLTE(FieldKeystrokes, v))
}

// AccuracyEQ applies the EQ predicate on the "accuracy" field.
func AccuracyEQ(v float64) predicate.Score {
	return predicate.Score(sql.FieldEQ(FieldAccuracy, v))
}

// AccuracyNEQ applies the NEQ predicate on the "accuracy" field.
func AccuracyNEQ(v float64) predicate.Score {
	return predicate.Score(sql.FieldNEQ(FieldAccuracy, v))
}

// AccuracyIn applies the In predicate on the "accuracy" field.
func AccuracyIn(vs ...float64) predicate.Score {
	return predicate.Score(sql.FieldIn(FieldAccuracy, vs...))
}

// AccuracyNotIn applies the NotIn predicate on the "accuracy" field.
func AccuracyNotIn(vs ...float64) predicate.Score {
	return predicate.Score(sql.FieldNotIn(FieldAccuracy, vs...))
}

// AccuracyGT applies the GT predicate on the "accuracy" field.
func AccuracyGT(v float64) predicate.Score {
	return predicate.Score(sql.FieldGT(FieldAccuracy, v))
}

// AccuracyGTE applies the GTE predicate on the "accuracy" field.
func AccuracyGTE(v float64) predicate.Score {
	return predicate.Score(sql.FieldGTE(FieldAccuracy, v))
}

// AccuracyLT applies the LT predicate on the "accuracy" field.
func AccuracyLT(v float64) predicate.Score {
	return predicate.Score(sql.FieldLT(FieldAccuracy, v))
}

// AccuracyLTE applies the LTE predicate on the "accuracy" field.
func AccuracyLTE(v float64) predicate.Score {
	return predicate.Score(sql.FieldLTE(FieldAccuracy, v))
}

// IsMaxKeystrokesEQ applies the EQ predicate on the "is_max_keystrokes" field.
func IsMaxKeystrokesEQ(v bool) predicate.Score {
	return predicate.Score(sql.FieldEQ(FieldIsMaxKeystrokes, v))
}

// IsMaxKeystrokesNEQ applies the NEQ predicate on the "is_max_keystrokes" field.
func IsMaxKeystrokesNEQ(v bool) predicate.Score {
	return predicate.Score(sql.FieldNEQ(FieldIsMaxKeystrokes, v))
}

// IsMaxKeystrokesIsNil applies the IsNil predicate on the "is_max_keystrokes" field.
func IsMaxKeystrokesIsNil() predicate.Score {
	return predicate.Score(sql.FieldIsNull(FieldIsMaxKeystrokes))
}

// IsMaxKeystrokesNotNil applies the NotNil predicate on the "is_max_keystrokes" field.
func IsMaxKeystrokesNotNil() predicate.Score {
	return predicate.Score(sql.FieldNotNull(FieldIsMaxKeystrokes))
}

// IsMaxAccuracyEQ applies the EQ predicate on the "is_max_accuracy" field.
func IsMaxAccuracyEQ(v bool) predicate.Score {
	return predicate.Score(sql.FieldEQ(FieldIsMaxAccuracy, v))
}

// IsMaxAccuracyNEQ applies the NEQ predicate on the "is_max_accuracy" field.
func IsMaxAccuracyNEQ(v bool) predicate.Score {
	return predicate.Score(sql.FieldNEQ(FieldIsMaxAccuracy, v))
}

// IsMaxAccuracyIsNil applies the IsNil predicate on the "is_max_accuracy" field.
func IsMaxAccuracyIsNil() predicate.Score {
	return predicate.Score(sql.FieldIsNull(FieldIsMaxAccuracy))
}

// IsMaxAccuracyNotNil applies the NotNil predicate on the "is_max_accuracy" field.
func IsMaxAccuracyNotNil() predicate.Score {
	return predicate.Score(sql.FieldNotNull(FieldIsMaxAccuracy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Score {
	return predicate.Score(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Score {
	return predicate.Score(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Score {
	return predicate.Score(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Score {
	return predicate.Score(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Score {
	return predicate.Score(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Score {
	return predicate.Score(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Score {
	return predicate.Score(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Score {
	return predicate.Score(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Score {
	return predicate.Score(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Score {
	return predicate.Score(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Score) predicate.Score {
	return predicate.Score(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Score) predicate.Score {
	return predicate.Score(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Score) predicate.Score {
	return predicate.Score(sql.NotPredicates(p))
}
